---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: argocd

components:
#  - ../../components/sealed-secrets-operator
#  - ../../components/gogs


resources:
   - namespace.yaml
   - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.2/manifests/install.yaml
   - route.yaml
#  - ../common/

